use_frameworks!

platform :ios, '10.0'

target 'OkHttpAndWebKitRequest_Example' do
  pod 'OkHttpAndWebKitRequest', :path => '../'

  target 'OkHttpAndWebKitRequest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
